/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaQueueRouteImport } from './routes/qa.queue'
import { Route as QaHistoryRouteImport } from './routes/qa.history'
import { Route as PartnerQueueRouteImport } from './routes/partner.queue'
import { Route as PartnerDashboardRouteImport } from './routes/partner.dashboard'
import { Route as PartnerCapacityRouteImport } from './routes/partner.capacity'
import { Route as MerchantRulesRouteImport } from './routes/merchant.rules'
import { Route as MerchantOrdersRouteImport } from './routes/merchant.orders'
import { Route as MerchantDashboardRouteImport } from './routes/merchant.dashboard'
import { Route as MerchantAnalyticsRouteImport } from './routes/merchant.analytics'
import { Route as QaReviewIdRouteImport } from './routes/qa.review.$id'
import { Route as PartnerJobsIdRouteImport } from './routes/partner.jobs.$id'
import { Route as MerchantOrdersIdRouteImport } from './routes/merchant.orders_.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaQueueRoute = QaQueueRouteImport.update({
  id: '/qa/queue',
  path: '/qa/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const QaHistoryRoute = QaHistoryRouteImport.update({
  id: '/qa/history',
  path: '/qa/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerQueueRoute = PartnerQueueRouteImport.update({
  id: '/partner/queue',
  path: '/partner/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/partner/dashboard',
  path: '/partner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerCapacityRoute = PartnerCapacityRouteImport.update({
  id: '/partner/capacity',
  path: '/partner/capacity',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRulesRoute = MerchantRulesRouteImport.update({
  id: '/merchant/rules',
  path: '/merchant/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/merchant/orders',
  path: '/merchant/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantDashboardRoute = MerchantDashboardRouteImport.update({
  id: '/merchant/dashboard',
  path: '/merchant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantAnalyticsRoute = MerchantAnalyticsRouteImport.update({
  id: '/merchant/analytics',
  path: '/merchant/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const QaReviewIdRoute = QaReviewIdRouteImport.update({
  id: '/qa/review/$id',
  path: '/qa/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerJobsIdRoute = PartnerJobsIdRouteImport.update({
  id: '/partner/jobs/$id',
  path: '/partner/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantOrdersIdRoute = MerchantOrdersIdRouteImport.update({
  id: '/merchant/orders_/$id',
  path: '/merchant/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/rules': typeof MerchantRulesRoute
  '/partner/capacity': typeof PartnerCapacityRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/queue': typeof PartnerQueueRoute
  '/qa/history': typeof QaHistoryRoute
  '/qa/queue': typeof QaQueueRoute
  '/merchant/orders/$id': typeof MerchantOrdersIdRoute
  '/partner/jobs/$id': typeof PartnerJobsIdRoute
  '/qa/review/$id': typeof QaReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/rules': typeof MerchantRulesRoute
  '/partner/capacity': typeof PartnerCapacityRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/queue': typeof PartnerQueueRoute
  '/qa/history': typeof QaHistoryRoute
  '/qa/queue': typeof QaQueueRoute
  '/merchant/orders/$id': typeof MerchantOrdersIdRoute
  '/partner/jobs/$id': typeof PartnerJobsIdRoute
  '/qa/review/$id': typeof QaReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/rules': typeof MerchantRulesRoute
  '/partner/capacity': typeof PartnerCapacityRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/queue': typeof PartnerQueueRoute
  '/qa/history': typeof QaHistoryRoute
  '/qa/queue': typeof QaQueueRoute
  '/merchant/orders_/$id': typeof MerchantOrdersIdRoute
  '/partner/jobs/$id': typeof PartnerJobsIdRoute
  '/qa/review/$id': typeof QaReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/merchant/analytics'
    | '/merchant/dashboard'
    | '/merchant/orders'
    | '/merchant/rules'
    | '/partner/capacity'
    | '/partner/dashboard'
    | '/partner/queue'
    | '/qa/history'
    | '/qa/queue'
    | '/merchant/orders/$id'
    | '/partner/jobs/$id'
    | '/qa/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/merchant/analytics'
    | '/merchant/dashboard'
    | '/merchant/orders'
    | '/merchant/rules'
    | '/partner/capacity'
    | '/partner/dashboard'
    | '/partner/queue'
    | '/qa/history'
    | '/qa/queue'
    | '/merchant/orders/$id'
    | '/partner/jobs/$id'
    | '/qa/review/$id'
  id:
    | '__root__'
    | '/'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/merchant/analytics'
    | '/merchant/dashboard'
    | '/merchant/orders'
    | '/merchant/rules'
    | '/partner/capacity'
    | '/partner/dashboard'
    | '/partner/queue'
    | '/qa/history'
    | '/qa/queue'
    | '/merchant/orders_/$id'
    | '/partner/jobs/$id'
    | '/qa/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  MerchantAnalyticsRoute: typeof MerchantAnalyticsRoute
  MerchantDashboardRoute: typeof MerchantDashboardRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantRulesRoute: typeof MerchantRulesRoute
  PartnerCapacityRoute: typeof PartnerCapacityRoute
  PartnerDashboardRoute: typeof PartnerDashboardRoute
  PartnerQueueRoute: typeof PartnerQueueRoute
  QaHistoryRoute: typeof QaHistoryRoute
  QaQueueRoute: typeof QaQueueRoute
  MerchantOrdersIdRoute: typeof MerchantOrdersIdRoute
  PartnerJobsIdRoute: typeof PartnerJobsIdRoute
  QaReviewIdRoute: typeof QaReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/queue': {
      id: '/qa/queue'
      path: '/qa/queue'
      fullPath: '/qa/queue'
      preLoaderRoute: typeof QaQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/history': {
      id: '/qa/history'
      path: '/qa/history'
      fullPath: '/qa/history'
      preLoaderRoute: typeof QaHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/queue': {
      id: '/partner/queue'
      path: '/partner/queue'
      fullPath: '/partner/queue'
      preLoaderRoute: typeof PartnerQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/dashboard': {
      id: '/partner/dashboard'
      path: '/partner/dashboard'
      fullPath: '/partner/dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/capacity': {
      id: '/partner/capacity'
      path: '/partner/capacity'
      fullPath: '/partner/capacity'
      preLoaderRoute: typeof PartnerCapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/rules': {
      id: '/merchant/rules'
      path: '/merchant/rules'
      fullPath: '/merchant/rules'
      preLoaderRoute: typeof MerchantRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/merchant/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/dashboard': {
      id: '/merchant/dashboard'
      path: '/merchant/dashboard'
      fullPath: '/merchant/dashboard'
      preLoaderRoute: typeof MerchantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/analytics': {
      id: '/merchant/analytics'
      path: '/merchant/analytics'
      fullPath: '/merchant/analytics'
      preLoaderRoute: typeof MerchantAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/review/$id': {
      id: '/qa/review/$id'
      path: '/qa/review/$id'
      fullPath: '/qa/review/$id'
      preLoaderRoute: typeof QaReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/jobs/$id': {
      id: '/partner/jobs/$id'
      path: '/partner/jobs/$id'
      fullPath: '/partner/jobs/$id'
      preLoaderRoute: typeof PartnerJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/orders_/$id': {
      id: '/merchant/orders_/$id'
      path: '/merchant/orders/$id'
      fullPath: '/merchant/orders/$id'
      preLoaderRoute: typeof MerchantOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  MerchantAnalyticsRoute: MerchantAnalyticsRoute,
  MerchantDashboardRoute: MerchantDashboardRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantRulesRoute: MerchantRulesRoute,
  PartnerCapacityRoute: PartnerCapacityRoute,
  PartnerDashboardRoute: PartnerDashboardRoute,
  PartnerQueueRoute: PartnerQueueRoute,
  QaHistoryRoute: QaHistoryRoute,
  QaQueueRoute: QaQueueRoute,
  MerchantOrdersIdRoute: MerchantOrdersIdRoute,
  PartnerJobsIdRoute: PartnerJobsIdRoute,
  QaReviewIdRoute: QaReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
